plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
  future: true
include:
  - index.md
  - 0831.md
  - 0909.md
  - 0916.md
  - 1001.md
  - 1005.md
  - 1021.md
  - 1023.md